[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.distutils-extra",
  "gcc",
  "gfortran",
  "pkg-config",
  "lapack",
  "blas"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python realtime_vibration_server_telegram_fixed.py"  # Ganti sesuai file utama kamu
