[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.distutils-extra"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python realtime_vibration_server_telegram_fixed.py"  # Ganti sesuai entry point kamu (misalnya: realtime_vibration_server_telegram.py)
