[phases.setup]
nixPkgs = [
  "python311Full",
  "pkg-config",
  "lapack",
  "blas"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python realtime_vibration_server_telegram_fixed.py"

